### ISSUE TITLE
gotok8s/kube-proxy:v1.14.7 not found: manifest unknown: manifest unknown

### ISSUE THREAD

**Issue by guoJohnny** [gotok8s/k8s-docker-desktop-for-mac#22]
Error response from daemon: manifest for gotok8s/kube-proxy:v1.14.7 not found: manifest unknown: manifest unknown
Error response from daemon: No such image: gotok8s/kube-proxy:v1.14.7
Error: No such image: gotok8s/kube-proxy:v1.14.7
Error response from daemon: manifest for gotok8s/kube-controller-manager:v1.14.7 not found: manifest unknown: manifest unknown
Error response from daemon: No such image: gotok8s/kube-controller-manager:v1.14.7
Error: No such image: gotok8s/kube-controller-manager:v1.14.7
Error response from daemon: manifest for gotok8s/kube-scheduler:v1.14.7 not found: manifest unknown: manifest unknown
Error response from daemon: No such image: gotok8s/kube-scheduler:v1.14.7
Error: No such image: gotok8s/kube-scheduler:v1.14.7
Error response from daemon: manifest for gotok8s/kube-apiserver:v1.14.7 not found: manifest unknown: manifest unknown
Error response from daemon: No such image: gotok8s/kube-apiserver:v1.14.7
Error: No such image: gotok8s/kube-apiserver:v1.14.7
![image](https://user-images.githubusercontent.com/46289237/67355353-aa6b6380-f589-11e9-8f07-d2efad033abc.png)

**Comment by maguowei** [comment]
v1.14.7 应该是和用的 docker-desktop 的stable 版本，当前这个项目只默认同步 edge版本所附带的k8s镜像，当前edge版本是 k8s 的1.15.4

**Comment by maguowei** [comment]
#24
