### ISSUE TITLE
如何能知道当前机器上的k8s版本依赖的镜像版本？

### ISSUE THREAD

**Issue by jiafeicat** [gotok8s/k8s-docker-desktop-for-mac#26]
像我的机器上目前是最新的V2.2.0.3，对应的k8s版本显示的是v1.15.5。
我修改了load_images.sh为1.15.5， 但是执行后发现k8s依然一直是starting中，应该还是镜像不对应导致的。

如果能查到当前版本的k8s需要的镜像是哪个版本的，或许这个问题就可以迎刃而解。
所以有什么方法吗？

**Comment by maguowei** [comment]
可以参考这个:  https://github.com/maguowei/actions/blob/c1d7fd51864159a1fe50ac5638ebc49a5d7e26b9/k8s-image-sync/entrypoint.sh#L10

```bash
获取版本镜像依赖
kubeadm config images list --kubernetes-version=${KUBERNETES_VERSION}
```

**Comment by jiafeicat** [comment]
> 可以参考这个: https://github.com/maguowei/actions/blob/c1d7fd51864159a1fe50ac5638ebc49a5d7e26b9/k8s-image-sync/entrypoint.sh#L10
> 
> ```shell
> 获取版本镜像依赖
> kubeadm config images list --kubernetes-version=${KUBERNETES_VERSION}
> ```
> 
> 或许需要在一台能访问外网的机器上执行

能否帮运行下kubeadm config images list --kubernetes-version=v1.15.5  当前找不到机器来执行 
非常感谢

**Comment by maguowei** [comment]
https://github.com/maguowei/iaas/runs/505088448?check_suite_focus=true#step:3:1
![截屏2020-03-13下午3 19 37](https://user-images.githubusercontent.com/7894483/76598563-1735c900-653e-11ea-92e2-4ee659122e91.png)

**Comment by jiafeicat** [comment]
> https://github.com/maguowei/iaas/runs/505088448?check_suite_focus=true#step:3:1
> ![截屏2020-03-13下午3 19 37](https://user-images.githubusercontent.com/7894483/76598563-1735c900-653e-11ea-92e2-4ee659122e91.png)

按着这个重新下载到了镜像。 但是依然是一直starting。 有日志可以看吗？

**Comment by maguowei** [comment]
@jiafeicat 首先确定所有镜像是否都已经pull 下来了
然后把这三条命令的输出贴一下
```bash
kubectl cluster-info
kubectl get nodes
kubectl describe node
```

**Comment by leeduckgo** [comment]
通过Resources > PROXIES 设置本地代理试试，我也是stable，把全部配置里的 v1.16.5 改成 v1.15.5 等一会就成功了。

**Comment by jiafeicat** [comment]
最终没有成功 暂时放弃了;
问题可能是: 1, 下载的不是上面的镜像,我的环境可能和上面的不一致. 2可能还需要其他的上面未列出的的镜像.
如果有日志看的话, 或许可以方便解决.
