### ISSUE TITLE
k8s镜像 v1.16.5找不到

### ISSUE THREAD

**Issue by xiangwangcheng** [gotok8s/k8s-docker-desktop-for-mac#27]
![image](https://user-images.githubusercontent.com/8049014/76975866-1b168080-696e-11ea-89a0-6147d7a18382.png)

**Comment by maguowei** [comment]
https://github.com/Azure/container-service-for-azure-china/blob/master/aks/README.md#22-container-registry-proxy 加个镜像加速试试
