### ISSUE TITLE
No such image: gotok8s/kube-controller-manager:latest

### ISSUE THREAD

**Issue by treasersimplifies** [gotok8s/k8s-docker-desktop-for-mac#28]
找不到镜像
```
$ ./load_images.sh
images found.
Using default tag: latest
Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
Error response from daemon: No such image: gotok8s/kube-controller-manager:latest
Error: No such image: gotok8s/kube-controller-manager
Using default tag: latest
Error response from daemon: manifest for gotok8s/kube-apiserver:latest not found: manifest unknown: manifest unknown
Error response from daemon: No such image: gotok8s/kube-apiserver:latest
Error: No such image: gotok8s/kube-apiserver
Using default tag: latest
Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: TLS handshake timeout
Error response from daemon: No such image: gotok8s/coredns:latest
Error: No such image: gotok8s/coredns
Using default tag: latest
Error response from daemon: manifest for gotok8s/pause:latest not found: manifest unknown: manifest unknown
Error response from daemon: No such image: gotok8s/pause:latest
Error: No such image: gotok8s/pause
Error response from daemon: Get https://registry-1.docker.io/v2/gotok8s/kube-proxy/manifests/v1.16.5: Get https://auth.docker.io/token?scope=repository%3Agotok8s%2Fkube-proxy%3Apull&service=registry.docker.io: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
Error response from daemon: No such image: gotok8s/kube-proxy:v1.16.5
Error: No such image: gotok8s/kube-proxy:v1.16.5
3.3.15-0: Pulling from gotok8s/etcd
Digest: sha256:37a8acab63de5556d47bfbe76d649ae63f83ea7481584a2be0dbffb77825f692
Status: Downloaded newer image for gotok8s/etcd:3.3.15-0
docker.io/gotok8s/etcd:3.3.15-0
Untagged: gotok8s/etcd:3.3.15-0
Untagged: gotok8s/etcd@sha256:37a8acab63de5556d47bfbe76d649ae63f83ea7481584a2be0dbffb77825f692
$ docker images
REPOSITORY                  TAG                 IMAGE ID            CREATED             SIZE
k8s.gcr.io/kube-proxy       v1.16.5             0ee1b8a3ebe0        2 months ago        82.7MB
k8s.gcr.io/kube-scheduler   v1.16.5             b4d073a9efda        2 months ago        83.5MB
k8s.gcr.io/etcd             3.3.15-0            b2756210eeab        7 months ago        247MB
```
registry-mirrors已经改了，但还是出现了上面的错误。而且我把images里的tag信息也都去掉了，也还是如此。

<img width="750" alt="image" src="https://user-images.githubusercontent.com/31153014/78333472-74acbb00-75bc-11ea-98c4-c145bad0aeae.png">

**Comment by maguowei** [comment]
tag 信息是不能省略的，需要明确指定版本，请贴一下指定版本时的报错

**Comment by treasersimplifies** [comment]
> @treasersimplifies tag 信息是不能省略的，需要明确指定版本，请贴一下指定版本时的报错
将v1.16.5改成了v1.15.5（我自己的Kubernetes的版本）后的报错：
```
$ ./load_images.sh
images found.
Error response from daemon: Get https://registry-1.docker.io/v2/gotok8s/kube-controller-manager/manifests/v1.15.5: Get https://auth.docker.io/token?scope=repository%3Agotok8s%2Fkube-controller-manager%3Apull&service=registry.docker.io: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
Error response from daemon: No such image: gotok8s/kube-controller-manager:v1.15.5
Error: No such image: gotok8s/kube-controller-manager:v1.15.5
v1.15.5: Pulling from gotok8s/kube-apiserver
39fafc05754f: Already exists 
88e18b69dd95: Pull complete 
Digest: sha256:d9fccd50f56c0f16dd55d2d708f4f71106c518ae92bf7a8d11d5db9d9dfb0fbc
Status: Downloaded newer image for gotok8s/kube-apiserver:v1.15.5
docker.io/gotok8s/kube-apiserver:v1.15.5
Untagged: gotok8s/kube-apiserver:v1.15.5
Untagged: gotok8s/kube-apiserver@sha256:d9fccd50f56c0f16dd55d2d708f4f71106c518ae92bf7a8d11d5db9d9dfb0fbc
Error response from daemon: manifest for gotok8s/coredns:v1.15.5 not found: manifest unknown: manifest unknown
Error response from daemon: No such image: gotok8s/coredns:v1.15.5
Error: No such image: gotok8s/coredns:v1.15.5
Error response from daemon: manifest for gotok8s/pause:v1.15.5 not found: manifest unknown: manifest unknown
Error response from daemon: No such image: gotok8s/pause:v1.15.5
Error: No such image: gotok8s/pause:v1.15.5
Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
Error response from daemon: No such image: gotok8s/kube-proxy:v1.15.5
Error: No such image: gotok8s/kube-proxy:v1.15.5
3.3.15-0: Pulling from gotok8s/etcd
Digest: sha256:37a8acab63de5556d47bfbe76d649ae63f83ea7481584a2be0dbffb77825f692
Status: Downloaded newer image for gotok8s/etcd:3.3.15-0
docker.io/gotok8s/etcd:3.3.15-0
Untagged: gotok8s/etcd:3.3.15-0
```

**Comment by maguowei** [comment]
> > @treasersimplifies tag 信息是不能省略的，需要明确指定版本，请贴一下指定版本时的报错
> 
> 将v1.16.5改成了v1.15.5（我自己的Kubernetes的版本）后的报错：
> 
> ```
> $ ./load_images.sh
> images found.
> Error response from daemon: Get https://registry-1.docker.io/v2/gotok8s/kube-controller-manager/manifests/v1.15.5: Get https://auth.docker.io/token?scope=repository%3Agotok8s%2Fkube-controller-manager%3Apull&service=registry.docker.io: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
> Error response from daemon: No such image: gotok8s/kube-controller-manager:v1.15.5
> Error: No such image: gotok8s/kube-controller-manager:v1.15.5
> v1.15.5: Pulling from gotok8s/kube-apiserver
> 39fafc05754f: Already exists 
> 88e18b69dd95: Pull complete 
> Digest: sha256:d9fccd50f56c0f16dd55d2d708f4f71106c518ae92bf7a8d11d5db9d9dfb0fbc
> Status: Downloaded newer image for gotok8s/kube-apiserver:v1.15.5
> docker.io/gotok8s/kube-apiserver:v1.15.5
> Untagged: gotok8s/kube-apiserver:v1.15.5
> Untagged: gotok8s/kube-apiserver@sha256:d9fccd50f56c0f16dd55d2d708f4f71106c518ae92bf7a8d11d5db9d9dfb0fbc
> Error response from daemon: manifest for gotok8s/coredns:v1.15.5 not found: manifest unknown: manifest unknown
> Error response from daemon: No such image: gotok8s/coredns:v1.15.5
> Error: No such image: gotok8s/coredns:v1.15.5
> Error response from daemon: manifest for gotok8s/pause:v1.15.5 not found: manifest unknown: manifest unknown
> Error response from daemon: No such image: gotok8s/pause:v1.15.5
> Error: No such image: gotok8s/pause:v1.15.5
> Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
> Error response from daemon: No such image: gotok8s/kube-proxy:v1.15.5
> Error: No such image: gotok8s/kube-proxy:v1.15.5
> 3.3.15-0: Pulling from gotok8s/etcd
> Digest: sha256:37a8acab63de5556d47bfbe76d649ae63f83ea7481584a2be0dbffb77825f692
> Status: Downloaded newer image for gotok8s/etcd:3.3.15-0
> docker.io/gotok8s/etcd:3.3.15-0
> Untagged: gotok8s/etcd:3.3.15-0
> 
> $ docker images
> REPOSITORY                  TAG                 IMAGE ID            CREATED             SIZE
> k8s.gcr.io/kube-proxy       v1.16.5             0ee1b8a3ebe0        2 months ago        82.7MB
> k8s.gcr.io/kube-scheduler   v1.16.5             b4d073a9efda        2 months ago        83.5MB
> k8s.gcr.io/kube-apiserver   v1.15.5             e534b1952a0d        5 months ago        207MB
> k8s.gcr.io/etcd             3.3.15-0            b2756210eeab        7 months ago        247MB
> ```
> 
> docker engine的配置：
> 
> ```
> {
>   "debug": true,
>   "experimental": true,
>   "registry-mirrors": [
>     "https://dockerhub.azk8s.cn"
>   ]
> }
> ```


1. 看上去你那边网络从docker hub pull镜像有问题，`docker hub `处于半被墙的状态。可以通过各种镜像加速的源试试。

2. 镜像的标签不能乱用，并不是所有镜像都是用的kubernetes 版本作为标签，请参考这个 获取v1.15.5对应的各镜像版本  https://github.com/gotok8s/k8s-docker-desktop-for-mac/issues/26#issuecomment-598585685
