### ISSUE TITLE
如果想用正式release的话image文件里面的版本怎么找

### ISSUE THREAD

**Issue by ThanksSirAlex** [gotok8s/k8s-docker-desktop-for-mac#32]
目前的正式release是k8s v1.15.5。这个没什么问题，但是etcd，coredns这些的版本怎么找

**Comment by maguowei** [comment]
@ThanksSirAlex  参考这个：https://github.com/gotok8s/k8s-docker-desktop-for-mac/issues/26#issuecomment-598581181

**Comment by ThanksSirAlex** [comment]
@maguowei 看样子是这个命令是要先装一个k8s才行？

**Comment by maguowei** [comment]
只要能执行 `kubeadm` 命令就行

@ThanksSirAlex  ![截屏2020-04-28 下午2 24 16](https://user-images.githubusercontent.com/7894483/80454039-f7c2f600-895b-11ea-9468-409e6707b96c.png)

https://github.com/maguowei/iaas/runs/625018072?check_suite_focus=true#step:3:28

**Comment by ThanksSirAlex** [comment]
@maguowei 搞明白了，是我装的kubeadm版本太新了，查不到1.15.5，多谢
